### PR TITLE
chore: get github action tag dynamically

### PR DESCRIPTION
**Pull request by ivan-tymoshenko**
This allows us to make the code the same in all branches and show the user a nice error if he misspells the tag.

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Review by mcollina — CHANGES_REQUESTED** [review]
I'm -1 to this. We should not expose our staging and dev environments in this way.

**Comment by ivan-tymoshenko** [comment]
> I'm -1 to this. We should not expose our staging and dev environments in this way.

How should we expose it then? Now it's anyway exposed through the .env file.
https://github.com/platformatic/onestep/blob/b01e0c9012e6d3fa69005c7b09b3932b300edd39/.env#L1

**Comment by ivan-tymoshenko** [comment]
We can pass it as an action env variable. So if you want to deploy it somewhere else except production, you would have to add a DEPLOY_SERVICE_HOST env variable to the action script.

**Comment by mcollina** [comment]
> We can pass it as an action env variable. So if you want to deploy it somewhere else except production, you would have to add a DEPLOY_SERVICE_HOST env variable to the action script.

Yes, exactly

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
