### PR TITLE
Support deploying subdirectory

### PR DESCRIPTION
**Pull request by abdelrazzaq-dev**
suuport deploying a subdirectory by setting pathToProject to the platformatic_project_path input or to the current working directory
this way if we have monorepo we can use  `working-directory`  to set the directory were to run all our steps https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaults

### CODE REVIEW

**Comment by abdelrazzaq-dev** [comment]
I need to update the tests because they depend on GITHUB_WORKSPACE

**Comment by abdelrazzaq-dev** [comment]
All the current tests pass, do you think we need to add a test for this feature?

**Review by mcollina — APPROVED** [review]
lgtm

**Review by ivan-tymoshenko — CHANGES_REQUESTED** [review]
It's already possible. If you want to deploy from a subdirectory, you should specify a path to the config file in a subdirectory. Just like the start command works.

**Comment by abdelrazzaq-dev** [comment]
> It's already possible. If you want to deploy from a subdirectory, you should specify a path to the config file in a subdirectory. Just like the start command works.

I already tried that and did not work for me, you can check the following workspace `01ee745f-8d0a-42ff-99dd-a0a056f24558`
I think that because we are based on `GITHUB_WORKSPACE` to build the path to the project files.

**Comment by ivan-tymoshenko** [comment]
Hmm, after a second check, I can't find this functionality. Probably it wasn't merged for some reason. Anyway I would use a config path to find the project dir instead of creating a new param basically because we do the same in the plt cli.

[here](https://github.com/platformatic/onestep/pull/13) is a pr that wasn't merged.

**Comment by ivan-tymoshenko** [comment]
@mcollina WDYT?

**Comment by abdelrazzaq-dev** [comment]
The following function that archives the project only considers the `pathToProject` for finding the project
https://github.com/platformatic/onestep/blob/c958b828ce372f39d261a2c0c97b6a68ff446e54/node_modules/%40platformatic/deploy-client/index.js#LL239C15-L239C15

**Comment by abdelrazzaq-dev** [comment]
Ah OK, I see how your solution works :+1:

**Comment by mcollina** [comment]
@abdelrazzaq-dev would you mind adding a bit of docs in the README of this project documenting how to set up running everything in a subdirectory?

**Comment by abdelrazzaq-dev** [comment]
> @abdelrazzaq-dev would you mind adding a bit of docs in the README of this project documenting how to set up running everything in a subdirectory?

In fact, while I was updating the readme I noticed for monorepo it's cleaner to use the `working-directory` parameter only without the `platformatic_project_path` input cause we always need to add that param elsewhere we need to navigate manually to the correct subdirectory for all steps.

**Comment by mcollina** [comment]
@abdelrazzaq-dev I'm sorry I've lost your message! Are you still waiting for me on this one?

**Comment by abdelrazzaq-dev** [comment]
Hello @mcollina yes this feature will help us deploy monorepos on Platformatic Cloud

**Comment by mcollina** [comment]
Thanks, this was added in #39 by @ivan-tymoshenko

**Pull request closed without merging**
